# Generated by Django 5.1.5 on 2025-01-30 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('craft', models.CharField(choices=[('Crochet', 'Crochet'), ('Knitting', 'Knitting')], max_length=10)),
                ('yarn_weight', models.CharField(choices=[('Lace/2 ply', 'Lace'), ('Light Fingering/3 ply', 'Light Fingering'), ('Fingering/4 ply (14 wpi)', 'Fingering'), ('Sport/5 ply (12 wpi)', 'Sport'), ('DK/8 ply (11 wpi)', 'Dk'), ('Aran/10 ply (8 wpi)', 'Aran'), ('Chunky/12 ply (7 wpi)', 'Chunky'), ('Super Chunky/16 ply (5-6 wpi)', 'Super Chunky')], max_length=30)),
                ('size', models.CharField(blank=True, choices=[('One Size', 'One Size'), ('XS', 'Xs'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'Xl')], max_length=10, null=True)),
                ('category', models.CharField(blank=True, choices=[('Clothing', 'Clothing'), ('Accessories', 'Accessories'), ('Toys and Hobbies', 'Toys And Hobbies'), ('Pet', 'Pet'), ('Home', 'Home')], max_length=20, null=True)),
                ('pdf_url', models.URLField(blank=True, max_length=255, null=True)),
                ('images', models.TextField()),
                ('videos', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatternHooksNeedles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Hook', 'Hook'), ('Needle', 'Needle')], max_length=10)),
                ('hook_size', models.CharField(blank=True, choices=[('2.0 mm', 'Size 2 0'), ('2.25 mm', 'Size 2 25'), ('2.5 mm', 'Size 2 5'), ('2.75 mm', 'Size 2 75'), ('3.0 mm', 'Size 3 0'), ('3.25 mm', 'Size 3 25'), ('3.5 mm', 'Size 3 5'), ('3.75 mm', 'Size 3 75'), ('4.0 mm', 'Size 4 0'), ('4.5 mm', 'Size 4 5'), ('5.0 mm', 'Size 5 0'), ('5.5 mm', 'Size 5 5'), ('6.0 mm', 'Size 6 0'), ('6.5 mm', 'Size 6 5'), ('7.0 mm', 'Size 7 0'), ('8.0 mm', 'Size 8 0'), ('9.0 mm', 'Size 9 0'), ('10.0 mm', 'Size 10 0'), ('12.0 mm', 'Size 12 0'), ('15.0 mm', 'Size 15 0'), ('20.0 mm', 'Size 20 0')], max_length=10, null=True)),
                ('needle_size', models.CharField(blank=True, choices=[('2.0 mm / US 0', 'Size 2 0'), ('2.25 mm / US 1', 'Size 2 25'), ('2.5 mm / US 1.5', 'Size 2 5'), ('2.75 mm / US 2', 'Size 2 75'), ('3.0 mm / US 2.5', 'Size 3 0'), ('3.25 mm / US 3', 'Size 3 25'), ('3.5 mm / US 4', 'Size 3 5'), ('3.75 mm / US 5', 'Size 3 75'), ('4.0 mm / US 6', 'Size 4 0'), ('4.5 mm / US 7', 'Size 4 5'), ('5.0 mm / US 8', 'Size 5 0'), ('5.5 mm / US 9', 'Size 5 5'), ('6.0 mm / US 10', 'Size 6 0'), ('6.5 mm / US 10.5', 'Size 6 5'), ('7.0 mm / US 10.75', 'Size 7 0'), ('8.0 mm / US 11', 'Size 8 0'), ('9.0 mm / US 13', 'Size 9 0'), ('10.0 mm / US 15', 'Size 10 0'), ('12.0 mm / US 17', 'Size 12 0'), ('15.0 mm / US 19', 'Size 15 0'), ('20.0 mm / US 36', 'Size 20 0')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.pattern')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.pattern')),
            ],
        ),
        migrations.AddField(
            model_name='pattern',
            name='hook_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patterns.patternhooksneedles'),
        ),
    ]
