# Generated by Django 5.1.5 on 2025-01-31 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternhooksneedles',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_hooks_needles', to='patterns.pattern'),
        ),
    ]
