# Generated by Django 5.1.5 on 2025-02-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
