# Generated by Django 5.1.5 on 2025-02-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0002_alter_pattern_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='pattern',
        ),
        migrations.AddField(
            model_name='library',
            name='pattern',
            field=models.ManyToManyField(blank=True, null=True, related_name='libraries', to='patterns.pattern'),
        ),
    ]
