# Generated by Django 5.1.5 on 2025-01-31 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0003_alter_library_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patterns.pattern'),
        ),
    ]
