# Generated by Django 5.1.5 on 2025-02-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0003_remove_library_pattern_library_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='pattern',
            field=models.ManyToManyField(blank=True, related_name='libraries', to='patterns.pattern'),
        ),
    ]
