# Generated by Django 5.1.5 on 2025-01-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0004_alter_library_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternhooksneedles',
            name='type',
            field=models.IntegerField(choices=[(0, 'Hook'), (1, 'Needle')], default=0),
            preserve_default=False,
        ),
    ]
