# Generated by Django 5.1.5 on 2025-01-31 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0005_alter_patternhooksneedles_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatternHooksNeedles',
            new_name='PatternHooksNeedle',
        ),
    ]
