# Generated by Django 5.1.5 on 2025-02-08 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0005_favourite_delete_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='patterns.pattern'),
        ),
    ]
